name: Test CD

on:
  push:
    branches: [ master, auth ]

env:
  SERVER_HOST: 91.200.151.163
  SERVER_USERNAME: root
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Connect to server and deploy changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd ~/MMX-API/
          git pull
          npm install
          pm2 restart mmx-api
